typography_spectrum: 0.6889242408797145
color:
  brandStrength: 0.258404002757743
  lightness: 0.003315732581540942
  saturation: 0.7712646969594061
  rhythmicContrast: 0.7374439702834934
  brandColors:
    - '#000000'
    - '#263248'
    - '#7E8AA2'
    - '#FFFFFF'
    - '#FF9800'
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/73d2897c-04f9-4a6c-a1f1-f9aa4dfb08fb.jpg
  appId: www.facebook.com/topsincflorida
layout_spectrum: 0.1730916548985988
author:
  name: Tops Inc
  email: sales@topsinc.net
  url: www.topsinc.net
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/b7899014-a780-4013-a3cc-e0380b1b1820.jpg
name: Tops Inc
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/a5ca28d8-aa73-48b9-8d81-2361eb0e6c44.jpg
title: 'providing not just a service but an experience '
