typography_spectrum: 0.2657385354395956
color:
  brandStrength: 0.9038044279441237
  lightness: 0.5451371856033802
  saturation: 0.04167209845036268
  rhythmicContrast: 0.4916868594009429
  brandColors:
    - '#16193B'
    - '#35478C'
    - '#4E7AC7'
    - '#7FB2F0'
    - '#ADD5F7'
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/73d2897c-04f9-4a6c-a1f1-f9aa4dfb08fb.jpg
  appId: www.facebook.com/topsincflorida
layout_spectrum: 0.5500190323218703
author:
  name: Tops Inc
  email: sales@topsinc.net
  url: www.topsinc.net
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/b7899014-a780-4013-a3cc-e0380b1b1820.jpg
name: Tops Inc
navigation:
  - id: 79eee89d-0db6-45c7-bab6-ec4f09800ea1
    url: 2016-07-14-man-behind-the-seams.html
    name: Behind the Seams
    type: content
  - id: ce70841d-8f87-4dc6-8ede-092e50246b06
    url: 2016-07-18-getting-an-estimate.html
    name: First Visit
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/a5ca28d8-aa73-48b9-8d81-2361eb0e6c44.jpg
title: 'Not Just a Service but an Experience '
